<?php


namespace SkyCentrics\Cloud\DTO\Device;


interface DeviceTypeInterface
{
    const TYPE_RADIO_THERMOSTAT_CT_30 = 241;
    const TYPE_RADIO_THERMOSTAT_CT_32 = 240;
    const TYPE_RADIO_THERMOSTAT_CT_50 = 243;
    const TYPE_RADIO_THERMOSTAT_CT_80 = 242;

    const TYPE_ISLAND_AIRE_PTAC = 105;
    const TYPE_EMERSON = 7;
    const TYPE_MITSUBISHI = 9;
    const TYPE_GENERIC_THERMOSTAT = 239;

    const TYPE_AO_SMITH_ELECTRIC_RESISTANCE = 106;
    const TYPE_AO_SMITH_HEAT_PUMP = 107;
    const TYPE_EMERSON_SWITCH = 5;
    const TYPE_GE = 109;
    const TYPE_VAUGHN = 108;
    const TYPE_GENERIC_WATER_HEATER = 112;
    const TYPE_CLIPPER_CREEK = 110;
    const TYPE_SIEMENS = 8;
    const TYPE_GENERIC_EV_CHARGER = 113;
    const TYPE_PENTAIR = 111;
    const TYPE_GENERIC_POOL_PUMP = 114;
    const TYPE_SKYPLUG_110 = 3;
    const TYPE_GENERIC_METERING_PLUG = 2;
    const TYPE_PISNAP_3 = 250;

    const TYPE_THERMOSTAT_DEPRECATED = 1;
    const TYPE_PISNAP_3_DEPRECATED = 4;
    const TYPE_SKYSNAP_10_DEPRECATED = 5;
    const TYPE_SMARTPLUG_3_DEPRECATED = 3;
    const TYPE_6_DEPRECATED = 6;

    const TYPE_CAMERAS = 0;
}
